### ISSUE TITLE
Plugin load error in CentOS 6

### ISSUE THREAD

**Issue by thomastaylor312** [intelsdi-x/snap-plugin-collector-iostat#11]
Loading the plugin on a CentOS 6 machine fails with:

```
Error loading plugin:
GetMetricTypes call error : exit status 1
```

and the only details in the logs are:

```
DEBU[2016-07-19T20:27:23Z] Getting plugin config                         _block_=getPluginConfigDataNode _module=config config-cache-key=0:iostat:4 config-cache-value=&{mutex:0xc8202ce3d0 t
able:map[]}
ERRO[2016-07-19T20:27:23Z] error in getting metric types                 _block=load-plugin _module=control-plugin-mgr error=GetMetricTypes call error : exit status 1 plugin-type=collector
ERRO[2016-07-19T20:27:23Z] GetMetricTypes call error : exit status 1     _module=_mgmt-rest
DEBU[2016-07-19T20:27:23Z] Removing file (/tmp/495148713/snap-plugin-collector-iostat)  _module=_mgmt-rest
INFO[2016-07-19T20:27:23Z] API response                                  _module=_mgmt-rest index=1 method=POST status=Internal Server Error status-code=500 url=/v1/plugins
```

I validated that this happens on 6.6 and 6.8, but it does not occur with 7.2.

This was all done using the latest v0.15-beta of Snap and the plugins

**Comment by thomastaylor312** [comment]
I debugged this a bit more and found that it was related to the version of iostat available in CentOS 6, which doesn't have all of the flags available that need to be there

**Comment by lynxbat** [comment]
We should patch this to handle the missing flags dynamically. Leaving open.

**Comment by thomastaylor312** [comment]
@lynxbat I was going off of a TODO in the code that said only sysstat > 10.2 would have the guaranteed behavior. We should make sure to remove that when we work on a patch
