### ISSUE TITLE
Expensive CPU time for CollectMetrics

### ISSUE THREAD

**Issue by felipewd** [intelsdi-x/snap-plugin-collector-iostat#15]
My environment:
- Slackware 14.2;
- Go 1.6.3;
- 15 devices in iostat;

This plugin when collecting `/intel/linux/iostat/device/*/*` in 1s intervals takes 32% CPU per collect, which seems excessive to me.

Using 'iostat -xd 1' uses 0.4%.

Don't know if this is fixable, but it appears that the job of this plugin is "just" to get the output of iostat into a snap-compatible format, right? I don't why it takes _this_ much CPU time for this.

@IRCody, would you mind adding @intelsdi-x/plugin-maintainers to this issue? Thanks :)

**Comment by mjbrender** [comment]
@intelsdi-x/plugin-maintainers

**Comment by IRCody** [comment]
Looks like @mjbrender beat me to it!

**Comment by nanliu** [comment]
I've added some large test to look into this further (#24). Initial testing shows around 28s cpu time to gather metric at 1s interval 500 times. I'm not sure if this grows significantly if the number of disk increases, and I'll try to access a system with more disks for comparison.

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  564 root      20   0   14592  12308   5068 S   3.7  0.6   0:28.86 snap-plugin-col
  199 root      20   0   35440  31352  10524 S   0.3  1.5   0:04.69 snapteld
```

**Comment by katarzyna-z** [comment]
Based on the fact the issue cannot  be reproduced (probably it's HW dependent). Please reopen that if you would like to continue discussion.
