### ISSUE TITLE
Plugin is not compatible with Docker

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap-plugin-collector-iostat#9]
The iostat plugin is based on the `iostat` Unix command. When executed in a Docker container the `iostat` command obviously reports statistics for devices/partitions of the container itself. Instead, the user probably expects that the iostat plugin collect devices/partitions statistics for the host. But we cannot make iostat read sys and proc information from other paths than `/proc` and `/sys`, so maybe using the iostat plugin makes no sense when snapd is executed in a Docker container. In that case we could just add a note the plugin README mentioning that the plugin is not compatible with Docker.

This issue relates to https://github.com/intelsdi-x/snap-plugin-collector-df/issues/8.

**Comment by tiffanyfj** [comment]
@elemoine Could you please look at my PR fix and give a thumbs up/LGTM if it solves your issue? Merci.

**Comment by tiffanyfj** [comment]
Plugin is actually compatible with Docker. Closing.
